spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5444/stc-dev}
    username: stc-dev
    password: stc-dev@123
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: postgresql

  flyway:
    enabled: false


